---
# Ref: https://golangci-lint.run/usage/configuration/
linters:
  enable:
    # golangci-lint default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck 
    - unused
    # added as suggested
    # uses go fmt
    - gofmt 
    # uses go imports
    - goimports
    - lll
    - misspell
    - mnd
    - nolintlint
    # replacement for go lint
    - revive 
    - usestdlibvars
    - wsl